apiVersion: core.kubefed.k8s.io/v1alpha1
kind: EnableTypeDirective
metadata:
  name: services
## TODO(marun) enable status generation
# spec:
#   status:
#     kind: FederatedServiceStatus
#   enableStatus: true
