
# Users add deps lines here

required = [
    "github.com/kubernetes/repo-infra/verify/boilerplate/test",
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    ]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
  [[prune.project]]
    name = "github.com/kubernetes/repo-infra"
    non-go = false
    unused-packages = false

# k8s.io/kubectl wants master of apimachinery and client-go, but
# kubebuilder is pinning to the version below.  Until kubectl comes
# pinned to versions compatible with kubebuilder, it will be necessary
# to maintain overrides.

[[override]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/client-go"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/api"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/kube-aggregator"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/apiextensions-apiserver"
  version="kubernetes-1.14.1"

[[override]]
  name="k8s.io/apiserver"
  version="kubernetes-1.14.1"

[[override]]
  name="github.com/openshift/generic-admission-server"
  revision="30a7ee0ea2ba57c5701e636ba5fef406d6e5ddc8"

[[override]]
  name="k8s.io/kube-openapi"
  revision="18908d120c6bdee559200d65ed8b8de9d253ccac"

[[override]]
  name="sigs.k8s.io/structured-merge-diff"
  revision="e85c7b244fd2cc57bb829d73a061f93a441e63ce"

[[override]]
  name = "github.com/coreos/etcd"
    revision="v3.3.1"

[[override]]
  name = "github.com/prometheus/client_golang"
    revision="v0.9.2"


# Note: Stanzas below are generated by Kubebuilder and may be rewritten when
# upgrading kubebuilder versions.

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[override]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.2.0"

[[override]]
  name="sigs.k8s.io/controller-tools"
  version="v0.2.0"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
