# Default values for kubefed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Configuration values for kubefed controllermanager deployment.
##
controllermanager:
  enabled: true
  replicaCount: 2
  repository: quay.io/kubernetes-multicluster
  image: kubefed
  tag: canary
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  clusterAvailableDelay:
  clusterUnavailableDelay:
  leaderElectLeaseDuration:
  leaderElectRenewDeadline:
  leaderElectRetryPeriod:
  clusterHealthCheckPeriodSeconds:
  clusterHealthCheckFailureThreshold:
  clusterHealthCheckSuccessThreshold:
  clusterHealthCheckTimeoutSeconds:
  ## Supported options are `configmaps` and `endpoints`
  leaderElectResourceLock:
  syncController:
    skipAdoptingResources:
  ## Value of feature gates item should be either `true` or `false`
  featureGates:
    PushReconciler:
    SchedulerPreferences:
    CrossClusterServiceDiscovery:
    FederatedIngress:

## Configuration global values for all charts
##
global:
  ## Whether the kubefed namespace will be the only target for federation.
  ## If unset, will default to `Cluster`. Supported options are `Cluster` and `Namespaced`
  scope: ""
