---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: federatedtypeconfigs.core.kubefed.io
spec:
  group: core.kubefed.io
  names:
    kind: FederatedTypeConfig
    listKind: FederatedTypeConfigList
    plural: federatedtypeconfigs
    shortNames:
    - ftc
    singular: federatedtypeconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: "FederatedTypeConfig programs KubeFed to know about a single API
        type - the \"target type\" - that a user wants to federate. For each target
        type, there is a corresponding FederatedType that has the following fields:
        \n - The \"template\" field specifies the basic definition of a federated
        resource - The \"placement\" field specifies the placement information for
        the federated   resource - The \"overrides\" field specifies how the target
        resource should vary across   clusters."
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FederatedTypeConfigSpec defines the desired state of FederatedTypeConfig.
          properties:
            federatedType:
              description: Configuration for the federated type that defines (via
                template, placement and overrides fields) how the target type should
                appear in multiple cluster.
              properties:
                group:
                  description: Group of the resource.
                  type: string
                kind:
                  description: Camel-cased singular name of the resource (e.g. ConfigMap)
                  type: string
                pluralName:
                  description: Lower-cased plural name of the resource (e.g. configmaps).  If
                    not provided, it will be computed by lower-casing the kind and
                    suffixing an 's'.
                  type: string
                scope:
                  description: Scope of the resource.
                  type: string
                version:
                  description: Version of the resource.
                  type: string
              required:
              - kind
              - pluralName
              - scope
              - version
              type: object
            propagation:
              description: Whether or not propagation to member clusters should be
                enabled.
              type: string
            statusCollection:
              description: Whether or not Status object should be populated.
              type: string
            statusType:
              description: Configuration for the status type that holds information
                about which type holds the status of the federated resource. If not
                provided, the group and version will default to those provided for
                the federated type api resource.
              properties:
                group:
                  description: Group of the resource.
                  type: string
                kind:
                  description: Camel-cased singular name of the resource (e.g. ConfigMap)
                  type: string
                pluralName:
                  description: Lower-cased plural name of the resource (e.g. configmaps).  If
                    not provided, it will be computed by lower-casing the kind and
                    suffixing an 's'.
                  type: string
                scope:
                  description: Scope of the resource.
                  type: string
                version:
                  description: Version of the resource.
                  type: string
              required:
              - kind
              - pluralName
              - scope
              - version
              type: object
            targetType:
              description: The configuration of the target type. If not set, the pluralName
                and groupName fields will be set from the metadata.name of this resource.
                The kind field must be set.
              properties:
                group:
                  description: Group of the resource.
                  type: string
                kind:
                  description: Camel-cased singular name of the resource (e.g. ConfigMap)
                  type: string
                pluralName:
                  description: Lower-cased plural name of the resource (e.g. configmaps).  If
                    not provided, it will be computed by lower-casing the kind and
                    suffixing an 's'.
                  type: string
                scope:
                  description: Scope of the resource.
                  type: string
                version:
                  description: Version of the resource.
                  type: string
              required:
              - kind
              - pluralName
              - scope
              - version
              type: object
          required:
          - federatedType
          - propagation
          - targetType
          type: object
        status:
          description: FederatedTypeConfigStatus defines the observed state of FederatedTypeConfig
          properties:
            observedGeneration:
              description: ObservedGeneration is the generation as observed by the
                controller consuming the FederatedTypeConfig.
              format: int64
              type: integer
            propagationController:
              description: PropagationController tracks the status of the sync controller.
              type: string
            statusController:
              description: StatusController tracks the status of the status controller.
              type: string
          required:
          - observedGeneration
          - propagationController
          type: object
      required:
      - spec
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
