{{- if not .Values.global.limitedScope }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federation-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: federation-role
subjects:
- kind: ServiceAccount
  name: federation-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
