{{ if (or (not .Values.global.limitedScope) (not (.Capabilities.APIVersions.Has "core.federation.k8s.io/v1alpha1"))) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: clusterpropagatedversions.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: ClusterPropagatedVersion
    plural: clusterpropagatedversions
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            clusterVersions:
              items:
                properties:
                  clusterName:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            overridesVersion:
              type: string
            templateVersion:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedclusters.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedCluster
    plural: federatedclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterRef:
              type: object
            secretRef:
              type: object
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastProbeTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            region:
              type: string
            zone:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedservicestatuses.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedServiceStatus
    plural: federatedservicestatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        clusterStatus:
          items:
            properties:
              clusterName:
                type: string
              status:
                type: object
            type: object
          type: array
        kind:
          type: string
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federatedtypeconfigs.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederatedTypeConfig
    plural: federatedtypeconfigs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            enableStatus:
              type: boolean
            federatedType:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            namespaced:
              type: boolean
            propagationEnabled:
              type: boolean
            status:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
            target:
              properties:
                group:
                  type: string
                kind:
                  type: string
                pluralName:
                  type: string
                version:
                  type: string
              required:
              - kind
              type: object
          required:
          - target
          - namespaced
          - propagationEnabled
          - federatedType
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
            propagationController:
              type: string
            statusController:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federationconfigs.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: FederationConfig
    plural: federationconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: propagatedversions.core.federation.k8s.io
spec:
  group: core.federation.k8s.io
  names:
    kind: PropagatedVersion
    plural: propagatedversions
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            clusterVersions:
              items:
                properties:
                  clusterName:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            overridesVersion:
              type: string
            templateVersion:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: dnsendpoints.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: DNSEndpoint
    plural: dnsendpoints
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            endpoints:
              items:
                properties:
                  dnsName:
                    type: string
                  labels:
                    type: object
                  recordTTL:
                    format: int64
                    type: integer
                  recordType:
                    type: string
                  targets:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: domains.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: Domain
    plural: domains
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        domain:
          type: string
        kind:
          type: string
        metadata:
          type: object
        nameServer:
          type: string
      required:
      - domain
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: ingressdnsrecords.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: IngressDNSRecord
    plural: ingressdnsrecords
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            hosts:
              items:
                type: string
              type: array
            recordTTL:
              format: int64
              type: integer
          type: object
        status:
          properties:
            dns:
              items:
                properties:
                  cluster:
                    type: string
                  loadBalancer:
                    type: object
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: servicednsrecords.multiclusterdns.federation.k8s.io
spec:
  group: multiclusterdns.federation.k8s.io
  names:
    kind: ServiceDNSRecord
    plural: servicednsrecords
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            allowServiceWithoutEndpoints:
              type: boolean
            dnsPrefix:
              type: string
            domainRef:
              type: string
            externalName:
              type: string
            recordTTL:
              format: int64
              type: integer
          required:
          - domainRef
          type: object
        status:
          properties:
            dns:
              items:
                properties:
                  cluster:
                    type: string
                  loadBalancer:
                    type: object
                  region:
                    type: string
                  zone:
                    type: string
                type: object
              type: array
            domain:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/hook": crd-install
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: replicaschedulingpreferences.scheduling.federation.k8s.io
spec:
  group: scheduling.federation.k8s.io
  names:
    kind: ReplicaSchedulingPreference
    plural: replicaschedulingpreferences
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusters:
              type: object
            rebalance:
              type: boolean
            targetKind:
              type: string
            totalReplicas:
              format: int32
              type: integer
          required:
          - targetKind
          - totalReplicas
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
{{ end }}
