---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: federation-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: federation-controller
      containers:
      - args:
        - --federation-namespace=$(FEDERATION_NAMESPACE)
        command:
        - /root/controller-manager
        image: "{{ .Values.repository }}/{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: controller-manager
        resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
        env:
        - name: FEDERATION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
