{{- if .Values.global.limitedScope }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: federation-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: federation-role
subjects:
- kind: ServiceAccount
  name: federation-controller
  namespace: {{ .Release.Namespace }}
{{- end }}
