---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: secrets
spec:
  comparisonField: ResourceVersion
  namespaced: true
  override:
    group: primitives.federation.k8s.io
    kind: FederatedSecretOverride
    pluralName: federatedsecretoverrides
    version: v1alpha1
  placement:
    group: primitives.federation.k8s.io
    kind: FederatedSecretPlacement
    pluralName: federatedsecretplacements
    version: v1alpha1
  propagationEnabled: true
  target:
    kind: Secret
    pluralName: secrets
    version: v1
  template:
    group: primitives.federation.k8s.io
    kind: FederatedSecret
    pluralName: federatedsecrets
    version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedsecrets.primitives.federation.k8s.io
spec:
  group: primitives.federation.k8s.io
  names:
    kind: FederatedSecret
    plural: federatedsecrets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            template:
              properties:
                apiVersion:
                  type: string
                data:
                  additionalProperties:
                    format: byte
                    type: string
                  type: object
                kind:
                  type: string
                metadata:
                  properties:
                    annotations:
                      additionalProperties:
                        type: string
                      type: object
                    clusterName:
                      type: string
                    creationTimestamp:
                      format: date-time
                      type: string
                    deletionGracePeriodSeconds:
                      format: int64
                      type: integer
                    deletionTimestamp:
                      format: date-time
                      type: string
                    finalizers:
                      items:
                        type: string
                      type: array
                    generateName:
                      type: string
                    generation:
                      format: int64
                      type: integer
                    initializers:
                      properties:
                        pending:
                          items:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          type: array
                        result:
                          properties:
                            apiVersion:
                              type: string
                            code:
                              format: int32
                              type: integer
                            details:
                              properties:
                                causes:
                                  items:
                                    properties:
                                      field:
                                        type: string
                                      message:
                                        type: string
                                      reason:
                                        type: string
                                    type: object
                                  type: array
                                group:
                                  type: string
                                kind:
                                  type: string
                                name:
                                  type: string
                                retryAfterSeconds:
                                  format: int32
                                  type: integer
                                uid:
                                  type: string
                              type: object
                            kind:
                              type: string
                            message:
                              type: string
                            metadata:
                              properties:
                                continue:
                                  type: string
                                resourceVersion:
                                  type: string
                                selfLink:
                                  type: string
                              type: object
                            reason:
                              type: string
                          type: object
                      required:
                      - pending
                      type: object
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                    name:
                      type: string
                    namespace:
                      type: string
                    ownerReferences:
                      items:
                        properties:
                          apiVersion:
                            type: string
                          blockOwnerDeletion:
                            type: boolean
                          controller:
                            type: boolean
                          kind:
                            type: string
                          name:
                            type: string
                          uid:
                            type: string
                        required:
                        - apiVersion
                        - kind
                        - name
                        - uid
                        type: object
                      type: array
                    resourceVersion:
                      type: string
                    selfLink:
                      type: string
                    uid:
                      type: string
                  type: object
                stringData:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  type: string
              type: object
          type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedsecretplacements.primitives.federation.k8s.io
spec:
  group: primitives.federation.k8s.io
  names:
    kind: FederatedSecretPlacement
    plural: federatedsecretplacements
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterNames:
              items:
                type: string
              type: array
          type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedsecretoverrides.primitives.federation.k8s.io
spec:
  group: primitives.federation.k8s.io
  names:
    kind: FederatedSecretOverride
    plural: federatedsecretoverrides
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            overrides:
              items:
                properties:
                  clusterName:
                    type: string
                  clusterOverrides:
                    items:
                      properties:
                        path:
                          type: string
                        value:
                          anyOf:
                          - type: string
                          - type: integer
                          - type: boolean
                          - type: object
                          - type: array
                      type: object
                    type: array
                type: object
              type: array
          type: object
  version: v1alpha1
