# Default values for federation-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Configuration values for federation v2 controllermanager deployment.
##
controllermanager:
  enabled: true
  replicaCount: 1
  repository: quay.io/kubernetes-multicluster
  image: federation-v2
  tag: canary
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  ## The cluster registry namespace.
  ## If unset, will default to kube-multicluster-public for a cluster-scoped deployment,
  ## and the federation namespace for namespace-scoped deployment.
  registryNamespace:
  clusterAvailableDelay:
  clusterUnavailableDelay:
  leaderElectLeaseDuration:
  leaderElectRenewDeadline:
  leaderElectRetryPeriod:
  clusterHealthCheckPeriodSeconds:
  clusterHealthCheckFailureThreshold:
  clusterHealthCheckSuccessThreshold:
  clusterHealthCheckTimeoutSeconds:
  ## Supported options are `configmaps` and `endpoints`
  leaderElectResourceLock:
  ## Value of feature gates item should be either `true` or `false`
  featureGates:
    PushReconciler:
    SchedulerPreferences:
    CrossClusterServiceDiscovery:
    FederatedIngress:


## Configuration values for federation v2 clusterregistry.
##
clusterregistry:
  enabled: true

## Configuration global values for all charts
##
global:
  ## Whether the federation namespace will be the only target for federation.
  ## If unset, will default to `Cluster`. Supported options are `Cluster` and `Namespaced`
  scope: ""
