apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedConfigMap
  metadata:
    name: test-configmap
    namespace: test-namespace
  spec:
    template:
      data:
        A: ala ma kota
