apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedDeploymentOverride
  metadata:
    name: test-deployment
    namespace: test-namespace
  spec:
    overrides:
    - clustername: cluster2
      replicas: 5
