apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedConfigMapPlacement
  metadata:
    name: test-configmap
    namespace: test-namespace
  spec:
    clusterNames:
    - cluster2
    - cluster1
