apiVersion: v1
kind: List
items:
- apiVersion: federation.k8s.io/v1alpha1
  kind: FederatedConfigMapOverride
  metadata:
    name: test-configmap
    namespace: test-namespace
  spec:
    overrides:
    - clustername: cluster2
      data:
        foo: bar
